### ISSUE TITLE
RDNA3/7900XTX support

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/MIOpen#2342]
HI,
I'm trying to test ML stuff with my 7900XTX and am having issues with the latest MIOpen. I built tensorflow-upstream with RDNA3 support (https://1drv.ms/u/s!AiqVlRyhZQZtiJF5cBtF39kAWfAsqw?e=CxtIBI) and it works OK using ROCm5.6. However, if I install it in the latest MIOpen docker image, it crashes with the following error.

> 2023-08-29 14:45:10.883603: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleLoadData(&module, data)' failed with 'hipErrorInvalidKernelFile'
> 
> 2023-08-29 14:45:10.883628: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleGetFunction(&function, module, kernel_name)' failed with 'hipErrorInvalidHandle'
> 
> 2023-08-29 14:45:10.883640: W tensorflow/core/framework/op_kernel.cc:1827] INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
Traceback (most recent call last):
  File "/pwd/Downloads/bench.py", line 15, in <module>
    mod = tf.keras.Sequential([tf.keras.layers.InputLayer(inp_units), tf.keras.layers.Dense(2500, activation='relu'), tf.keras.layers.Dense(2500, activation='relu'), tf.keras.layers.Dense(250, activation='relu'), tf.keras.layers.Dense(nclasses, activation='softmax')])
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/trackable/base.py", line 204, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.9/dist-packages/keras/src/backend.py", line 2100, in random_uniform
    return tf.random.stateless_uniform(
tensorflow.python.framework.errors_impl.InternalError: {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle' [Op:Sub] name: 

Does AMD plan to release RDNA3 support in 5.7? or Do we need to wait for 6.0. I see references to both versions being worked on and was hoping that it would be released sooner rather than later. 

By the way, 7900XTX tensorflow performance is very bad. I wanted to confirm myself the benchmark numbers from https://cprimozic.net/notes/posts/machine-learning-benchmarks-on-the-7900-xtx/ and that's how I found this problem. I was hoping that ROCm5.7 woudl resolve the performance issue but I can't even get it to run. :(

**Comment by briansp2020** [comment]
I'm using a docker image from https://hub.docker.com/r/rocm/miopen/tags, ci_a15150 which was built a few days ago.

**Comment by briansp2020** [comment]
I got some more benchmark numbers.
https://github.com/RadeonOpenCompute/ROCm/issues/2098#issuecomment-1705482476

Direct link to git gist at https://gist.github.com/briansp2020/e885f0eb6cbec45fcaf0c2eac8c3ee11

**Comment by briansp2020** [comment]
BTW, I noticed that many of ROCmSoftwarePlatform docker images from https://hub.docker.com/u/rocm uses different base images. For containers that are not working on sub-components (tensorflow, pytorch, triton?), they should use same base image. It seems like all of them use different and use up too much space. Also, I had to figure out the environment every time I tried out a different container. They all had different Python verions (I saw 3.9, 3.10, 3.11 from both Ubuntu repo and conda) It will make people's lives much easier if AMD can standardize on the base image and python version. Not sure how easy that is to be honest since AI/ML is developing very fast and every body seems to have their own way of setting up their environment. But it would be helpful if AMD could standardize as much as possible.

**Comment by dmikushin** [comment]
AFAIK, images in https://hub.docker.com/u/rocm are not for end-users. End-users should work with the official releases of their framework of choice - TF, PyTorch, Triton, etc. Every framework decides what is the most appropriate for their community, such as the best version of Python and its type. Standardization would have to override those decisions to the extend, which requires a separate customer support track for each framework, along with thier dependencies.

**Comment by briansp2020** [comment]
@dmikushin
Though I agree that not all containers there are for end-users, it just seemed too fragmented. So much so that if people are trying to understand components of ROCm so that they can eventually contribute to AMD's open-source effort, they will have a tough time getting up to speed.

Also, I think it's a good idea for AMD to release ROCm+TF, ROCm+PT, ROCm+Triton reference docker images. Sure they can push that responsibility upstream. But since it takes time for the upstream to incorporate ROCm specific changes, it would be nice if AMD maintained a up-to-date container and/or instructions to set up end-user-facing ML/AI environments & examples using AMD hardware. As smaller player in ML/AI space, ROCm will not get as much attention from the upstream folks and AMD should promote ROCm on their own.

[evshiron](https://github.com/evshiron) has a nice page with containers for various AI examples. It's a bit stale and it would be nice for AMD to officially have such a project to show people how to set up popular projects using AMD hardware.

Just my 2 cents.

**Comment by dmikushin** [comment]
@briansp2020 I would personally take a deep breath and accept the fragmentation as it is now. Otherwise, any generous attempt to reduce fragmentation would result into just one more piece of fragmentation. There is often a fragmentation even between two hands: Jupyter's own docker image is conda, however jupyterhub is mainline Python. Life is pain.

**Comment by briansp2020** [comment]
https://xkcd.com/927/

![image](https://github.com/ROCmSoftwarePlatform/MIOpen/assets/3746601/16dbf6f7-ae06-49bd-8882-02ce158d4809)

**Comment by briansp2020** [comment]
BTW. It would be nice to hear from people who know whether the 7900XTX performance issue is mainly from MIOpen or if there are other issues that need to be resolved. I have linked all 7900XTX issue tickets that mention TensorFlow to this one since I was assuming that once MIOpen is properly optimized for 7900XTX, the main issue will be resolved.

I have not linked 7900XTX issues that mention PyTorch only to this because I don't know whether MIOpen is the main bottleneck there as well.

Also, am I correct to assume that, eventually, GFX1100 will have its own kernels written in assembly? I don't see any files with gfx1100 in the name in src/kernels directory. So, I assumed 7900XTX has not seen any optimization at all other than compiler improvements. Is that a correct assumption? Sorry to ask so many questions but I'm very excited to see that we are very close to seeing the full potential of 7900XTX in ML/AI. It would be nice to know how much performance we can expect to get out of 7900XTX versus how much we are currently getting.

**Comment by wsippel** [comment]
gfx1100 already has its own optimized kernels - you have to search for gfx11, not gfx1100. And ROCm by and large works for me, on a 7900XTX. It's a bit buggy, might leak memory and can get the entire kernel driver to enter a bad state and crash after a while, I certainly hope that'll be fixed. From my experience, when it works, Torch is mostly fine, Tensorflow is wonky and slow, and Triton is hot garbage on RDNA3 at this point. Don't know if ROCm 5.7 will improve things (I sure hope so!), but I believe some RDNA3 specific tweaks and optimizations are scheduled for ROCm 6.0.

**Comment by briansp2020** [comment]
@wsippel 
What version of PyTorch are you using? I wasted 2 days trying to get Pytorch to run on my 7900XTX. The officially released version (PyTorch 2.0.1 for ROCm5.4.2) crashes when I try to create a variable on the GPU, which is understandable since it was released a long time ago.

However, the latest nightly build for ROCm 5.6 did not work either. It was driving me crazy because I was able to run some PyTorch code at some point in the past when trying out different configurations. It turned out that the only nightly build for ROCm5.5 is somewhat working. It seems their automated nightly build system is broken. I understand that things will break during development (ex. ROCm 5.7 test build has issues with TensorFlow at the moment) But ROCm5.6 is a released version and a nightly build for it should not fail so catastrophically...

BTW, I see files with gfx11 in the name in src/kernels directory. But I do not see any packages with gfx11 in the name. All I see are
```
miopen-hip-gfx1030-36kdb5.6.1
miopen-hip-gfx900-56kdb5.6.1 
miopen-hip-gfx900-64kdb5.6.1 
miopen-hip-gfx906-60kdb5.6.1 
miopen-hip-gfx906-64kdb5.6.1 
miopen-hip-gfx908-120kdb5.6.1
miopen-hip-gfx90a-104kdb5.6.1
miopen-hip-gfx90a-110kdb5.6.1
```
Should there be a miopen package for gfx11?

Also, do you know if there is an instruction on how to build PyTorch for ROCm? I can build TensorFlow & MIOpen. But I haven't seen the instructions on how to build PyTorch for ROCm.

Any pointer will be appreciated!

**Comment by wsippel** [comment]
The missing kdb files are not an issue as far as I understand, missing kernels are compiled at runtime. And you have to use Pytorch nightlies. Pytorch comes bundled with its own copy of ROCm, stable still ships with ROCm 5.4, and you need at least 5.5 for RDNA3 support. And I've also noticed that some nightlies bundled with 5.6 don't work, so I use the ones with 5.5 on those days. Or you can build Pytorch 2.0 with gfx11 support if you want, it's what I did during ROCm 5.5 beta. I wrote those instructions back then for Stable Diffusion, might be a little outdated but should hopefully still work (for use in a Python venv):
```
export PYTORCH_ROCM_ARCH="gfx1100"
export CMAKE_PREFIX_PATH=[PATH TO YOUR VENV GOES HERE]
wget https://github.com/pytorch/pytorch/releases/download/v2.0.0/pytorch-v2.0.0.tar.gz
tar -xzvf pytorch-v2.0.0.tar.gz && cd pytorch-v2.0.0
pip install cmake ninja
pip install -r requirements.txt
pip install mkl mkl-include
python3 tools/amd_build/build_amd.py
python3 setup.py install
```

**Comment by briansp2020** [comment]
@wsippel 
Thank you for the instruction. I followed your instructions and built it using ROCm5.6.1 and am getting the same error as using the nightly build.
```
(venv) root@rocm-ubuntu:~# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.0a0'
>>> ls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ls' is not defined
>>> x=torch.rand(20000000, 128, device = 'cuda')
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.10/site-packages/torch/_tensor.py", line 426, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/root/venv/lib/python3.10/site-packages/torch/_tensor_str.py", line 636, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/root/venv/lib/python3.10/site-packages/torch/_tensor_str.py", line 567, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/root/venv/lib/python3.10/site-packages/torch/_tensor_str.py", line 327, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/root/venv/lib/python3.10/site-packages/torch/_tensor_str.py", line 115, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: HIP error: the operation cannot be performed in the present state
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

>>>
```

I'll try building with ROCm5.5 and see if that helps.

**Comment by wsippel** [comment]
Weird...
```
Python 3.11.5 (main, Aug 28 2023, 20:02:58) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.1.0.dev20230827+rocm5.6'
>>> torch.cuda.is_available()
True
>>> torch.version.hip
'5.6.31061-8c743ae5d'
>>> torch.cuda.get_device_name(0)
'AMD Radeon RX 7900 XTX'
>>> x=torch.rand(20000000, 128, device = 'cuda')
>>> x
tensor([[0.5519, 0.3130, 0.8105,  ..., 0.1176, 0.5674, 0.1628],
        [0.4238, 0.6082, 0.1566,  ..., 0.8261, 0.5781, 0.2428],
        [0.9779, 0.4911, 0.8231,  ..., 0.9800, 0.3798, 0.9466],
        ...,
        [0.5105, 0.2872, 0.3043,  ..., 0.1184, 0.1820, 0.3528],
        [0.9375, 0.1680, 0.7187,  ..., 0.2480, 0.0707, 0.4545],
        [0.2336, 0.9598, 0.3362,  ..., 0.3665, 0.1882, 0.4274]],
       device='cuda:0')
>>>
```

**Comment by ppanchad-amd** [comment]
@briansp2020 Please test with latest ROCm 6.1.2. If issue is resolved, please close ticket. Thanks!

**Comment by briansp2020** [comment]
I have tested pytorch with ROCm 6.x before and they seem to work now. I only wish that ROCm compatible versions of these frame work are distributed timely fashion. pip install tensorflow-rocm still does not work because https://pypi.org/project/tensorflow-rocm/ has not updated after https://github.com/ROCm/tensorflow-upstream/issues/2524 was fixed month ago.
