### ISSUE TITLE
Trying to compile hipCaffe with MIOpen

### ISSUE THREAD

**Issue by SNUmed** [ROCmSoftwarePlatform/MIOpen#3]
I am trying to compile hipCaffe with MIOpen in Ubuntu 16.04 with RX480 and Xeon 1231 v3.
I followed the installation manual in the hipCaffe page and succeded compiling without MIOpen but when I try it with MIOpen by modifying Makefile.config, it failes resulting the following error.
`CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/layer.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/hdf5.cpp
In file included from src/caffe/util/db_lmdb.cpp:2:
In file included from ./include/caffe/util/db_lmdb.hpp:10:
In file included from ./include/caffe/util/db.hpp:6:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/db_lmdb.o' failed
make: *** [.build_release/src/caffe/util/db_lmdb.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/caffe/util/hdf5.cpp:1:
In file included from ./include/caffe/util/hdf5.hpp:9:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/hdf5.o' failed
make: *** [.build_release/src/caffe/util/hdf5.o] Error 1
In file included from src/caffe/util/signal_handler.cpp:7:
In file included from ./include/caffe/util/signal_handler.h:5:
In file included from ./include/caffe/solver.hpp:7:
In file included from ./include/caffe/net.hpp:10:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/signal_handler.o' failed
make: *** [.build_release/src/caffe/util/signal_handler.o] Error 1
In file included from src/caffe/data_transformer.cpp:8:
In file included from ./include/caffe/data_transformer.hpp:6:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/data_transformer.o' failed
make: *** [.build_release/src/caffe/data_transformer.o] Error 1
In file included from src/caffe/util/math_functions.cpp:21:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/math_functions.o' failed
make: *** [.build_release/src/caffe/util/math_functions.o] Error 1
In file included from src/caffe/layer.cpp:2:
In file included from ./include/caffe/layer.hpp:8:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/layer.o' failed
make: *** [.build_release/src/caffe/layer.o] Error 1
In file included from src/caffe/util/blocking_queue.cpp:4:
In file included from ./include/caffe/data_reader.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:53:40: error: use of undeclared identifier 'miopenDouble'
  static const miopenDataType_t type = miopenDouble;
                                       ^
./include/caffe/util/cudnn.hpp:100:55: error: use of undeclared identifier 'miopenCrossCorrelation'; did you mean 'miopenConvolution'?
  MIOPEN_CHECK(miopenInitConvolutionDescriptor(*conv, miopenCrossCorrelation,
                                                      ^~~~~~~~~~~~~~~~~~~~~~
                                                      miopenConvolution
./include/caffe/util/cudnn.hpp:13:29: note: expanded from macro 'MIOPEN_CHECK'
    miopenStatus_t status = condition; \
                            ^
/usr/include/miopen.h:218:5: note: 'miopenConvolution' declared here
    miopenConvolution = 0, /*!< Convolutions */
    ^
2 errors generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/blocking_queue.o' failed
make: *** [.build_release/src/caffe/util/blocking_queue.o] Error 1
`
I built them with make -j8.

**Comment by SNUmed** [comment]
The original error I used to get was 
`CXX src/caffe/layer.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/benchmark.cpp
In file included from src/caffe/util/hdf5.cpp:1:
In file included from ./include/caffe/util/hdf5.hpp:9:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/hdf5.o' failed
make: *** [.build_release/src/caffe/util/hdf5.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/caffe/util/db_lmdb.cpp:2:
In file included from ./include/caffe/util/db_lmdb.hpp:10:
In file included from ./include/caffe/util/db.hpp:6:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/db_lmdb.o' failed
make: *** [.build_release/src/caffe/util/db_lmdb.o] Error 1
In file included from src/caffe/util/signal_handler.cpp:7:
In file included from ./include/caffe/util/signal_handler.h:5:
In file included from ./include/caffe/solver.hpp:7:
In file included from ./include/caffe/net.hpp:10:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/signal_handler.o' failed
make: *** [.build_release/src/caffe/util/signal_handler.o] Error 1
In file included from src/caffe/data_transformer.cpp:8:
In file included from ./include/caffe/data_transformer.hpp:6:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/data_transformer.o' failed
make: *** [.build_release/src/caffe/data_transformer.o] Error 1
In file included from src/caffe/util/math_functions.cpp:21:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/math_functions.o' failed
make: *** [.build_release/src/caffe/util/math_functions.o] Error 1
In file included from src/caffe/util/benchmark.cpp:3:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/benchmark.o' failed
make: *** [.build_release/src/caffe/util/benchmark.o] Error 1
In file included from src/caffe/layer.cpp:2:
In file included from ./include/caffe/layer.hpp:8:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/layer.o' failed
make: *** [.build_release/src/caffe/layer.o] Error 1
In file included from src/caffe/util/blocking_queue.cpp:4:
In file included from ./include/caffe/data_reader.hpp:8:
In file included from ./include/caffe/common.hpp:19:
In file included from ./include/caffe/util/device_alternate.hpp:48:
./include/caffe/util/cudnn.hpp:6:10: fatal error: 'miopen.h' file not found
#include <miopen.h>
         ^~~~~~~~~~
1 error generated.
Died at /opt/rocm/bin/hipcc line 452.
Makefile:624: recipe for target '.build_release/src/caffe/util/blocking_queue.o' failed
make: *** [.build_release/src/caffe/util/blocking_queue.o] Error 1
`
so I sym linked all the header files in /opt/rocm/miopen and etc to /usr/include.
then the resulting error looked like my original question.

**Comment by SNUmed** [comment]
Fixed after using hipCaffe-developer branch

**Comment by dagamayank** [comment]
cc\ @parallelo 
@SNUmed thanks. We also merged the `hip-develop` branch to `hip` branch on our end. So you can now use the `hip` branch.

Closing this issue as it was not a MIOpen issue per-se.
