### ISSUE TITLE
gfx1200 Windows MIOpen error

### ISSUE THREAD

**Issue by 0xDELUXA** [ROCmSoftwarePlatform/MIOpen#3862]
Ive built PyTorch for gfx1200 with RockBuilder from TheRock repo to use in stable diffusion image generation, the build was kind of successful, torch.cuda.is_available gives True output, torch.cuda.get_device_name is AMD RX 9060 XT.
My problem is that at the first step of the image generation, so for ex at 0/20, it gives this error no matter what I do with my build:

MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' naive_conv.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: naive_conv.cpp
MIOpen(HIP): Warning [BuildHip] warning: HIPRTC error log empty
MIOpen Error: E:/TheRock/ml-libs/MIOpen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: naive_conv.cpp
0%| | 0/20 [00:07<?, ?it/s]
!!! Exception during processing !!! miopenStatusUnknownError

**Comment by mirh** [comment]
https://github.com/ROCm/TheRock/issues/710 ?

**Comment by 0xDELUXA** [comment]
It looks the same but it isnt

**Comment by 0xDELUXA** [comment]
Managed to find a workaround, if I set MIOPEN_FIND_MODE=2, the image starts generating, but its very slow, like 20s/it. It also crashes my gpu giving oom error at the vae stage. Really convenient with 16gb

**Comment by mirh** [comment]
It isn't, because gfx1201 isn't gfx1200 of course
But as can be seen in the clr PR, that's sharing a similar fate in not being included.

**Comment by 0xDELUXA** [comment]
I see. And without people like @scottt, gfx1200 will not be included in the near future

**Comment by mirh** [comment]
Can you try to build this https://github.com/ROCm/clr/pull/169/files but with the navi44 reference?

**Comment by 0xDELUXA** [comment]
If only I understood these things...

**Comment by ppanchad-amd** [comment]
Hi @0xDELUXA. Internal ticket has been created to investigate this issue. Thanks!

**Comment by 0xDELUXA** [comment]
@ppanchad-amd wow thx

**Comment by 0xDELUXA** [comment]
Managed to find out that If I set MIOPEN_DEBUG_CONV_DIRECT=0, MIOpen starts to work for me

**Comment by ppanchad-amd** [comment]
@0xDELUXA Glad to hear it's working for you. Can we go ahead and close this ticket? Thanks!

**Comment by 0xDELUXA** [comment]
@ppanchad-amd This way the image starts generating, but after the last step, at vae stage, it crashes the gpu driver giving oom error no matter what other env var I set. If I disable miopen as a whole using torch.backends.cudnn.enabled=False inside the script, the generation is even slower, but at least it doesn't crash the driver at the end. So I don't think my issue is solved yet. Does anyone have the gfx1200 who can try miopen on their card too?

**Comment by earthdmitriy** [comment]
Hi! 
I'm using pytorch wheels from this repo https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x?ref=ai.rncz.net (unable to build them on my own).
I'm running comfyui and getting random miopenStatusUnknownError on some nodes. I noticed a pattern - some node settings are ok, some produce miopenStatusUnknownError 

For example with WanImageToVideo - not all "length" parameters are acceptable (most values produce miopenStatusUnknownError ). Acceptable length depends on width and height provided.
VaeDecodeTiled with Vae from Framepack -  I had to play with tile size until I found working combination.

MIOPEN_DEBUG_CONV_DIRECT=0 have no effect in my case.

Env - Windows 11 and RX9070XT

**Comment by 0xDELUXA** [comment]
> Hi! 
> I'm using pytorch wheels from this repo https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x?ref=ai.rncz.net (unable to build them on my own).
> I'm running comfyui and getting random miopenStatusUnknownError on some nodes. I noticed a pattern - some node settings are ok, some produce miopenStatusUnknownError 
> 
> For example with WanImageToVideo - not all "length" parameters are acceptable (most values produce miopenStatusUnknownError ). Acceptable length depends on width and height provided.
> VaeDecodeTiled with Vae from Framepack -  I had to play with tile size until I found working combination.
> 
> Env - Windows 11 and RX9070XT

Hi! This unknown error thing is more like a category. Miopen support on windows isnt that mature bc the officially available hip sdk 6.2.4 afaik doesn't even include miopen as a whole. Scottt's wheel does come with a bundled rocm, but miopen needs to make some changes and patches for windows, and I think these will not come till the official rocm 7 for windows release later in q3. Sadly

**Comment by taylding-amd** [comment]
Hi @0xDELUXA,

Our Windows support is still a work in progress and not yet fully mature. Would you be willing to try using Windows Subsystem for Linux (WSL) instead?

I've included instructions below on how to install ROCm and PyTorch with WSL, which should provide you with a more stable environment for your work.

[Instructions link/details here](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html)

Please let me know if you encounter any issues with the WSL setup.

**Comment by 0xDELUXA** [comment]
Hi @taylding-amd, 

Thank you, I'm actively using WSL for the time being, this page was also very helpful: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html

Just wanted to make an issue so you devs know that the gfx1200 has some problems on Windows. If you already knew this specific problem I can close this issue.

Ive built this pytorch wheel locally that's failing, and now Im waiting for TheRock devs to make their freshly-baked automatic windows pytorch wheel releases support gfx1200 too, then I will see if this is just a local error, or its not.

Thx again for your time.

**Comment by taylding-amd** [comment]
Hi @0xDELUXA,

Thank you for bringing this up and for sharing your experience.

I wanted to let you know that I’ve already discussed this issue with both TheRock and MIOpen teams. For MIOpen, the CI is currently only running on MI machines. Technically, it should work on Navi machines (including gfx1200), but since it hasn’t been tested extensively, we’re aware that some tests have failed on Navi hardware. The team is aware and will be working on improving support and coverage for these devices.

Regarding TheRock, the team has recently acquired some gfx1200 machines and will be running tests on them soon to help address these issues.

Thanks again for your patience and for helping us improve support for gfx1200 on Windows. Please feel free to share any additional details or logs if you encounter further issues, and I’ll keep you updated as we make progress.

**Comment by commontater888** [comment]
Here in March of 2026.  Rocm 7.2 is out, but the same Miopen problem plagues the gfx1200 on Windows.

**Comment by 0xDELUXA** [comment]
Indeed: https://github.com/ROCm/TheRock/issues/2591#issuecomment-4007683985
