### ISSUE TITLE
Memory access fault by GPU node-4. Reason: Page not present or supervisor privilege.

### ISSUE THREAD

**Issue by qili93** [ROCmSoftwarePlatform/MIOpen#731]
ROCM version: 3.9.1
MIOPEN version: 2.8.0
Datatype: FP32

Core dump when call `miopenFindConvolutionBackwardWeightsAlgorithm`

CONV OP

```c++
// input
const int batch_size = 100;
const int input_channel = 3;
const int input_height = 1;
const int input_width = 1;
// filter
const int output_channel = 120;
const int groups = 3;
const int kernel_h = 1;
const int kernel_w = 1;
// attr
const int conv_stride = 1;
const int conv_padding = 0;
const int conv_dilation = 1;
const std::string padding_algorithm = "EXPLICIT";
const std::string data_format = "NCHW";
const bool exhaustive_search = false;
```

MIOPEN LOG

```log
(base) liqi27@dfc97822c791:~/Github-qili93/Paddle-rocm/build_debug/paddle/fluid/operators {rocm_dev_0204} ./test_conv_op
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0205 11:47:23.068696  8925 paddle_gtest_main.cc:73] gtest env_string:--tryfromenv=fraction_of_gpu_memory_to_use,initial_gpu_memory_in_mb,reallocate_gpu_memory_in_mb,allocator_strategy
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from test_conv2d_cudnn_op
[ RUN      ] test_conv2d_cudnn_op.gpu_place
I0205 11:47:23.204515  8925 dynamic_loader.cc:168] Try to find library: libMIOpen.so from default system path.
CUDNN version is: 280
W0205 11:47:23.204653  8925 device_context.cc:385] Please NOTE: device: 0, GPU Compute Capability: 90.0, Driver API Version: 320.0, Runtime API Version: 3.0
W0205 11:47:23.204680  8925 device_context.cc:399] device: 0, MIOpen Version: 2.8.0
I0205 11:47:23.592720  8925 cuda_stream.cc:53] CUDAStream Init stream: 0x4747690, priority: 2
I0205 11:47:23.592947  8925 dynamic_loader.cc:168] Try to find library: librocblas.so from default system path.
MIOpen(HIP)   0.001: Info [Handle] stream: 0, device_id: 0
I0205 11:47:23.599571  8925 scope.cc:177] Create variable Input
I0205 11:47:23.599613  8925 scope.cc:177] Create variable Filter
I0205 11:47:23.599642  8925 scope.cc:177] Create variable Output
I0205 11:47:23.600059  8925 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 1536, and remaining 256
I0205 11:47:23.600113  8925 memcpy.cc:273] memory::Copy 1200 Bytes from CPUPlace to CUDAPlace(0) by thream(0x4747690)
I0205 11:47:23.600313  8925 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 768, and remaining 256
I0205 11:47:23.600339  8925 memcpy.cc:273] memory::Copy 480 Bytes from CPUPlace to CUDAPlace(0) by thream(0x4747690)
I0205 11:47:23.600759  8925 conv_op_test.cc:101] Op(conv2d), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))]}, outputs:{Output[Output:[0]({})()]}.
I0205 11:47:23.600782  8925 operator.cc:195] CUDAPlace(0) Op(conv2d), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))]}, outputs:{Output[Output:[0]({})()]}.
I0205 11:47:23.606954  8925 cuda_stream.cc:53] CUDAStream Init stream: 0x474f140, priority: 2
MIOpen(HIP)   8.068: Info [Handle] stream: 0, device_id: 0
I0205 11:47:23.607411  8925 operator.cc:1248] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN]
I0205 11:47:23.607599  8925 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 48384, and remaining 256
I0205 11:47:23.607659  8925 conv_cudnn_op.cu:93] Compute ConvOp with cuDNN: data_format=NCHW compute_format=NCHW
MIOpen(HIP)   0.554: Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP)   0.178: Info [HipCompilerVersionImpl] 3.9.20412
MIOpen(HIP)   0.022: Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.8.0.8183-19-600d591d
MIOpen(HIP)  14.334: Info [GetForwardSolutions] 
MIOpen(HIP)  69.604: Info [Measure] Db::Prefetch time: 69.4869 ms
MIOpen(HIP)   0.923: Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 0
MIOpen(HIP)   0.043: Info [GetForwardSolutions] 
MIOpen(HIP)   0.226: Info [CompileForwardSolution] solver_id = ConvOclDirectFwd
MIOpen(HIP)   7.969: Info [FindSolutionImpl] ConvOclDirectFwd
MIOpen(HIP)   1.728: Info [FindSolutionImpl] Perf Db: record not found for: ConvOclDirectFwd
MIOpen(HIP)   0.198: Info [KernDb] database not present
MIOpen(HIP)  12.301: Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoDirect 0.00976 0
MIOpen(HIP)   0.044: Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvOclDirectFwd , 0, 0.00976
I0205 11:47:23.715456  8925 conv_miopen_helper.h:156] miopenConvFwdAlgorithm_t choose algo 1
MIOpen(HIP)   0.078: Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP)   0.042: Info [GetForwardSolutions] 
MIOpen(HIP)   0.251: Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 100 -c 3 -H 1 -W 1 -k 120 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 3 -F 1 -t 1
MIOpen(HIP)   0.027: Info [ConvolutionForward] algo = 1, workspace = 0
I0205 11:47:23.715924  8925 operator.cc:229] CUDAPlace(0) Op(conv2d), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))]}, outputs:{Output[Output:float[100, 120, 1, 1]({})(CUDAPlace(0))]}.
I0205 11:47:23.716086  8925 conv_op_test.cc:107] Op(conv2d), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))]}, outputs:{Output[Output:float[100, 120, 1, 1]({})(CUDAPlace(0))]}.
I0205 11:47:23.716166  8925 memcpy.cc:243] memory::Copy 48000 Bytes from CUDAPlace(0) to CPUPlace by thream(0x4747690)
output_tensor dims is: [100, 120, 1, 1]
I0205 11:47:23.717190  8925 scope.cc:177] Create variable Input
I0205 11:47:23.717216  8925 scope.cc:177] Create variable Filter
I0205 11:47:23.717236  8925 scope.cc:177] Create variable Output@GRAD
I0205 11:47:23.717254  8925 scope.cc:177] Create variable Input@GRAD
I0205 11:47:23.717272  8925 scope.cc:177] Create variable Filter@GRAD
I0205 11:47:23.717308  8925 memcpy.cc:273] memory::Copy 1200 Bytes from CPUPlace to CUDAPlace(0) by thream(0x4747690)
I0205 11:47:23.717386  8925 memcpy.cc:273] memory::Copy 480 Bytes from CPUPlace to CUDAPlace(0) by thream(0x4747690)
I0205 11:47:23.717530  8925 memcpy.cc:273] memory::Copy 48000 Bytes from CPUPlace to CUDAPlace(0) by thream(0x4747690)
I0205 11:47:23.718372  8925 conv_op_test.cc:188] Op(conv2d_grad), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))], Output@GRAD[Output@GRAD:float[100, 120, 1, 1]({})(CUDAPlace(0))]}, outputs:{Filter@GRAD[Filter@GRAD:[0]({})()], Input@GRAD[Input@GRAD:[0]({})()]}.
I0205 11:47:23.718398  8925 operator.cc:195] CUDAPlace(0) Op(conv2d_grad), inputs:{Filter[Filter:float[120, 1, 1, 1]({})(CUDAPlace(0))], Input[Input:float[100, 3, 1, 1]({})(CUDAPlace(0))], Output@GRAD[Output@GRAD:float[100, 120, 1, 1]({})(CUDAPlace(0))]}, outputs:{Filter@GRAD[Filter@GRAD:[0]({})()], Input@GRAD[Input@GRAD:[0]({})()]}.
I0205 11:47:23.718492  8925 operator.cc:1248] expected_kernel_key:data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN]
I0205 11:47:23.718582  8925 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 1536, and remaining 256
I0205 11:47:23.718652  8925 auto_growth_best_fit_allocator.cc:97] Not found and reallocate 768, and remaining 256
I0205 11:47:23.718685  8925 conv_cudnn_op.cu:399] Compute ConvGradOp with cuDNN: data_format=NCHW compute_format=NCHW
MIOpen(HIP)   2.996: Info [BackwardDataGetWorkSpaceSize] 
MIOpen(HIP)   0.034: Info [GetBackwardSolutions] 
MIOpen(HIP)   0.207: Info [FindConvBwdDataAlgorithm] requestAlgoCount = 1, workspace = 0
MIOpen(HIP)   0.035: Info [GetBackwardSolutions] 
MIOpen(HIP)   0.177: Info [CompileBackwardSolution] solver_id = ConvOclDirectFwd
MIOpen(HIP)   0.043: Info [FindSolutionImpl] ConvOclDirectFwd
MIOpen(HIP)   1.852: Info [FindSolutionImpl] Perf Db: record not found for: ConvOclDirectFwd
MIOpen(HIP)   5.059: Info [FindConvBwdDataAlgorithm] miopenConvolutionBwdDataAlgoDirect 0.019521        0
MIOpen(HIP)   0.038: Info [FindConvBwdDataAlgorithm] BWD Chosen Algorithm: ConvOclDirectFwd , 0, 0.019521
I0205 11:47:23.726265  8925 conv_miopen_helper.h:206] miopenConvBwdDataAlgorithm_t choose algo 1
MIOpen(HIP)   0.041: Info [BackwardDataGetWorkSpaceSize] 
MIOpen(HIP)   0.015: Info [GetBackwardSolutions] 
MIOpen(HIP)   0.253: Info [BackwardWeightsGetWorkSpaceSize] 
MIOpen(HIP)   0.032: Info [GetWrwSolutions] 
MIOpen(HIP)   0.168: Info [GetWrwSolutionsFallback] Fallback path, GEMM
MIOpen(HIP)   0.132: Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP)   0.028: Info [GetPerformanceConfig] 2
MIOpen(HIP)   0.360: Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 100 -c 3 -H 1 -W 1 -k 120 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 3 -F 4 -t 1
MIOpen(HIP)   0.028: Info [FindConvBwdWeightsAlgorithm] requestAlgoCount = 1, workspace = 48000
MIOpen(HIP)   0.024: Info [GetWrwSolutions] 
MIOpen(HIP)   0.163: Info [GetWrwSolutionsFallback] Fallback path, GEMM
MIOpen(HIP)   0.153: Info [TryLoad] Find-db regenerating.
MIOpen(HIP)6743.820: Info [SetValues] 120-1-1-1x1-3-1-1-100-0x0-1x1-1x1-0-NCHW-FP32-W_g3, content inserted: miopenConvolutionBwdWeightsAlgoGEMM:gemm,6.176,0,rocBlas,<unused>
MIOpen(HIP)   0.243: Info [FindSolutionImpl] ConvOclBwdWrW53 (not searchable)
Memory access fault by GPU node-4 (Agent handle: 0x45d9f20) on address 0x7f07cb421000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

Append the core stack

```bash
(gdb) bt
#0  0x00007f4e4819c387 in raise () from /lib64/libc.so.6
#1  0x00007f4e4819da78 in abort () from /lib64/libc.so.6
#2  0x00007f4e47dae746 in rocr::core::Runtime::VMFaultHandler(long, void*) () from /opt/rocm/lib/libhsa-runtime64.so.1
#3  0x00007f4e47db066b in rocr::core::Runtime::AsyncEventsLoop(void*) () from /opt/rocm/lib/libhsa-runtime64.so.1
#4  0x00007f4e47d616c7 in rocr::os::ThreadTrampoline(void*) () from /opt/rocm/lib/libhsa-runtime64.so.1
#5  0x00007f4e4d19cea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f4e4826496d in clone () from /lib64/libc.so.6
(gdb) 
```

Please kindly help to comment how to resolve this issue, thanks !

**Comment by qili93** [comment]
It's really weird that the problem gone, after I manually run the MIOPEN command line and then execute the test executable binary again. While core dump always happen if I switch to a new docker environment.

Step 1: execute `./test_conv_op` then core dump with above logs and core stack
Step 2: execute `./bin/MIOpenDriver conv -n 100 -c 3 -H 1 -W 1 -k 120 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 3 -F 4 -t 1` under `/opt/rocm/miopen` directory, and runs successfully
Step 3:  execute `./test_conv_op`  again, and then no core dump happen

Logs of the above 3 steps attached here:
[step1.test_conv_op_log1.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5930001/step1.test_conv_op_log1.log)
[step2.miopen_command.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5930002/step2.miopen_command.log)
[step3.test_conv_op_log2.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5930003/step3.test_conv_op_log2.log)

Please kindly help to comment, thanks in advance :)

**Comment by atamazov** [comment]
Please try the following:
- upgrade to the recent MIOpen release
- use debug build of MIOpen

Let us know if the problem persists.

**Comment by qili93** [comment]
Close this issue as problem resolved after change to set filter tensor by api of "miopenSet4dTensorDescriptor" instead of "miopenSetTensorDescriptor"。
